# Generated by Django 3.2.13 on 2022-04-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResizeImageMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('resizeimagemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_profile.resizeimagemixin')),
                ('short_bio', models.CharField(max_length=255)),
                ('about_page_url', models.TextField()),
                ('profile_pic_url', models.ImageField(upload_to=user_profile.models.profile_pic_url)),
                ('profile_views', models.IntegerField(default=0)),
                ('accent_color', models.CharField(choices=[('#000000', 'BLACK'), ('#FFFFFF', 'WHITE')], max_length=7)),
                ('background_color', models.CharField(choices=[('#000000', 'BLACK'), ('#FFFFFF', 'WHITE')], max_length=7)),
                ('header_pic_url', models.ImageField(upload_to=user_profile.models.header_pic_url)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('user_profile.resizeimagemixin',),
        ),
    ]
